"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";
import ThemeSwitcher from "@/components/ThemeSwitcher";

/**
 * Terms and Conditions page containing the required AI healthcare boundaries
 * and medical disclaimers.
 */
export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 transition-colors duration-300">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-white/70 dark:bg-slate-900/60 border-b border-slate-200/50 dark:border-slate-800/40 backdrop-blur-md px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2 group text-sm font-bold text-slate-500 hover:text-slate-800 dark:hover:text-white transition-colors">
          <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </Link>
        <div className="flex items-center gap-4">
          <ThemeSwitcher />
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-3xl mx-auto px-6 py-12 space-y-8 text-left">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-brand-purple/10 border border-brand-purple/20 text-brand-purple rounded-2xl">
            <FileText className="h-8 w-8" />
          </div>
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-950 dark:text-white">
              Terms & Conditions
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-semibold mt-1">
              Last Updated: June 28, 2026
            </p>
          </div>
        </div>

        <section className="space-y-4 leading-relaxed">
          <p className="text-sm">
            Please read these Terms & Conditions carefully before using the UniCare web application. By accessing or using our services, you agree to comply with and be bound by these terms.
          </p>

          <h2 className="text-xl font-bold text-slate-900 dark:text-white pt-4">
            1. Scope of Service & Medical Disclaimer
          </h2>
          <p className="text-sm border-l-4 border-rose-500 pl-4 bg-rose-500/5 dark:bg-rose-500/10 py-3 rounded-r-lg">
            <strong>CRITICAL NOTICE:</strong> UniCare is an AI-powered educational and wellness companion application. It is NOT a medical device. The information, symptoms suggestions, diet formulas, exercise guidance, and voice responses provided by UniCare are for educational and informational purposes only. They are not intended to diagnose, treat, cure, or prevent any disease or medical condition.
          </p>
          <p className="text-sm">
            Never disregard professional medical advice or delay seeking it because of something you have read or heard through UniCare. If you are experiencing a medical emergency, call emergency services immediately.
          </p>

          <h2 className="text-xl font-bold text-slate-900 dark:text-white pt-4">
            2. Health Data Processing & Consent
          </h2>
          <p className="text-sm">
            By logging your metrics, biometrics (such as sleep, symptoms, activities, and meals), or chat messages, you grant UniCare the permission to process your health indicators to compile personalized summaries. We encrypt sensitive entries to protect your identity.
          </p>

          <h2 className="text-xl font-bold text-slate-900 dark:text-white pt-4">
            3. Account Responsibilities & Role Security
          </h2>
          <p className="text-sm">
            You are responsible for keeping your login credentials secure. Access is granted based on user roles (Admin/User). Admins possess permissions to check operational indices, whereas Users manage their personal wellness records.
          </p>

          <h2 className="text-xl font-bold text-slate-900 dark:text-white pt-4">
            4. Limitation of Liability
          </h2>
          <p className="text-sm">
            UniCare and its creators shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from your reliance on the AI chatbot responses, symptom logs, or wellness indicators generated by the platform.
          </p>
        </section>
      </main>
    </div>
  );
}
